# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jie-Think 
subtitle: blog
description: "jie blog"
keywords: 
author: jie
language: 
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x 

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:jie-think/jie-think.github.io.git
  branch: master






# 主题配置
materialx:
  # 导航栏
  nav_menu:
    - name: 主页
      slug: about
      fa:   home
      url: /
    - name: 项目
      slug: projects
      fa:   cube
      url: https://github.com/jie-think
    - name: 归档
      slug: archives
      fa:   archive
      url: /archives
  # 右边的小窗口
  widgets:
    - about # 显示个人头像、格言、社交信息等，如果注释掉这一行就不显示
    - categories # 显示分类
    - tagcloud # 显示tags
    - music # 显示自己的网易云歌单
    - links # 显示友链
    - toc # 显示目录
  widgets_about:
    title:
    motto: The only way to learn it is to do it.
    social: true
  # 网易云音乐歌单id
  widgets_musicid:
  -name:
     hppt://www.baidu.com
  # 侧边栏的友链
  widgets_links:
  # 页脚
  footer_social:
  - slug: envelope
    url: qq646958863@163.com
  - slug: github
    url: https://github.com/jie-think
  - slug: instagram
    url:
  - slug: google-plus
    url:
  - slug: twitter
    url:
  - slug: music
    url:

# 头像
avatar: "https://github.com/jie-think/github_blog_prd/blob/master/img/heard.jpg"

# 推荐文章
recommended_posts:
  autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  server: https://api.truelaurel.com # 后端推荐服务器地址
  timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  excludePattern: []
  titleHtml: <h4>推荐文章</h4> #自定义标题
  internalLinks: 3 # 内部文章数量
  externalLinks: 2 # 外部文章数量
  fixedNumber: false
